import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..', '..', '..');

test('Phase 4: Dist bundle generated by Vite build exists', () => {
  const distHtml = path.join(projectRoot, 'apps', 'desktop', 'dist', 'index.html');
  assert.ok(fs.existsSync(distHtml), 'apps/desktop/dist/index.html must exist after build');

  const content = fs.readFileSync(distHtml, 'utf8');
  assert.ok(content.includes('<div id="root">'), 'dist/index.html must contain root div');
});

test('Phase 4: Multi-turn message structure matches contract schema', () => {
  const session = {
    id: 'test-session-123',
    title: 'Multi-turn chat session',
    created_at: Date.now() / 1000,
    updated_at: Date.now() / 1000,
    working_directory: 'G:\\Project_Ned',
    model_profile: 'Mistral-Small-3.1-24B',
  };

  const messages = [
    { role: 'user', content: 'What is the current system status?' },
    {
      role: 'assistant',
      content: 'System is healthy and RTX 5090 is ready.',
      tool_calls: [
        {
          id: 'call_1',
          type: 'function',
          function: { name: 'system.info', arguments: '{}' },
        },
      ],
    },
    { role: 'tool', content: '{"os": "Windows 11", "gpu": "RTX 5090"}', tool_call_id: 'call_1' },
  ];

  assert.equal(session.title, 'Multi-turn chat session');
  assert.equal(messages.length, 3);
  assert.equal(messages[1].tool_calls[0].function.name, 'system.info');
});

test('Phase 4: Context budget contract thresholds', () => {
  const defaultMaxTokens = 32768;
  const defaultMaxToolChars = 4000;
  const longToolOutput = 'X'.repeat(5000);

  const excess = longToolOutput.length - defaultMaxToolChars;
  assert.ok(excess > 0, 'Long output must exceed threshold');
  assert.equal(defaultMaxTokens, 32768, 'Default context budget is 32K');
});
